### PR TITLE
Add feature multiple actions #66

### PR DESCRIPTION
**Pull request by rootcoma**
Multiple actions can overlap. Uses queue linked list to keep track of pos for area array. If multiple overlapping actions have the same button then both commands will be output, on separate lines.

### example
```
%{A:Hello:} click for 'Hello\n' %{A4:Scrolled:}%{A:World!:} click for 'Hello\nWorld!\n', scroll up for 'Scrolled\n' %{A}%{A}%{A}
```

### CODE REVIEW

**Comment by mrshankly** [comment]
Any reason why this hasn't been merged yet? It would be pretty nice to have this feature.

**Comment by LemonBoy** [comment]
Lack of time to review mostly, my main concern are the continuous malloc/free, I'd avoid that by allocating K areas the first time and then realloc if later a number of areas > K are needed.
I doubt the area number changes greatly (if at all) from the initial one, so I guess it's a good way to go :)
Feel free to chime in and suggest something else, I'm interested in merging this too...

**Comment by mrshankly** [comment]
I'd probably take a completely different approach. Only five buttons work on clickable areas, so maybe having a way to define a command for each button in a single `%{...}` block would be better.

Change the `area_t` struct to have a 5 element array of `char *`, one for each button. This way you wouldn't even need malloc, realloc or free. Here's an example.

Say I want to have a volume control area in my bar. I already have a command-line tool for this, `vol !` to toggle (mute/unmute), `vol + | -` to increase or decrease the volume by 5%. I could make it this way:

```
%{A1:vol !:4:vol -:5:vol +:} volume %{A}
```

The `area_t` struct for this would look something like:

```c
typedef struct area_t {
    int begin, end, align;
    xcb_window_t window;
    char *commands[5];
} area_t;

area_t volume = {
    .commands = { "vol !", NULL, NULL, "vol -", "vol +" }
};
```

One obvious disadvantage is that you can't nest areas with this approach, like in @rootcoma example. Because of this some stuff will be more verbose, since you'd have to use more clickable areas. I don't think this would be a problem though.

I've only skimmed over the code, I'm not sure how easy this would be to implement. Let me know what you think.

**Comment by otommod** [comment]
I also happened to write a patch for this and have send a pull request.

**Comment by LemonBoy** [comment]
@mrshankly 
I'd avoid hardcoding the actions in the code and nested areas aren't a big deal, I can't think of any good use of that feature
@otommod
Your approach looks very cool (and requires only minor modifications)

**Comment by mrshankly** [comment]
@LemonBoy
Actions are not hardcoded, you take the commands from the user input.

Anyway, @otommod approach looks good.

**Comment by otommod** [comment]
Well, my approach is basically what dzen2 does.
@LemonBoy If you want me to make any changes, just say so.

**Comment by LemonBoy** [comment]
I don't have enough time to test it thoroughly but if you confirm that it's stable after a couple of days of stress testing then I'll blindly merge it :)

**Pull request closed without merging**
