### PR TITLE
Enter leave events

### PR DESCRIPTION
**Pull request by siers**
Maybe you want this in your repo? I found it nice and use it in my panel repo for myself.

### CODE REVIEW

**Comment by siers** [comment]
Merge conflicts removed. 

Also, I made another [commit](https://github.com/siers/bar/commit/a85a4b20dd8732fc8ca26dc89c596890d7cd784a) in siers/bar:master that `sed -i s/bar/lemonbar/ .gitignore`.

**Comment by daGrevis** [comment]
:+1: 

Please add usage documentation before merging.

**Comment by siers** [comment]
It's lightly documented in both [README.pod](https://github.com/siers/bar/commit/b80138ea72be3df02a638a922babed604ec51af5) and in the [usage message](https://github.com/siers/bar/commit/7716a0b40859ea16898be230db3e203888f51f9d) printed by -h. Is there anything else I should document?

**Comment by siers** [comment]
Any chance of this ever getting merged?

**Pull request closed without merging**
